# Embedding like ConceptCLIP

spine_concepts = [
    "T1 vertebra healthy",
    "T1 vertebra anomaly block vertebra",
    "T1 vertebra anomaly butterfly vertebra",
    "T2 vertebra healthy",
    "T2 vertebra anomaly block vertebra",
    "T2 vertebra anomaly butterfly vertebra",
    "T3 vertebra healthy",
    "T3 vertebra anomaly block vertebra",
    "T3 vertebra anomaly butterfly vertebra",
    "T4 vertebra healthy",
    "T4 vertebra anomaly block vertebra",
    "T4 vertebra anomaly butterfly vertebra",
    "T5 vertebra healthy",
    "T5 vertebra anomaly block vertebra",
    "T5 vertebra anomaly butterfly vertebra",
    "T6 vertebra healthy",
    "T6 vertebra anomaly block vertebra",
    "T6 vertebra anomaly butterfly vertebra",
    "T7 vertebra healthy",
    "T7 vertebra anomaly block vertebra",
    "T7 vertebra anomaly butterfly vertebra",
    "T8 vertebra healthy",
    "T8 vertebra anomaly block vertebra",
    "T8 vertebra anomaly butterfly vertebra",
    "T9 vertebra healthy",
    "T9 vertebra anomaly block vertebra",
    "T9 vertebra anomaly butterfly vertebra",
    "T10 vertebra healthy",
    "T10 vertebra anomaly block vertebra",
    "T10 vertebra anomaly butterfly vertebra",
    "T11 vertebra healthy",
    "T11 vertebra anomaly block vertebra",
    "T11 vertebra anomaly butterfly vertebra",
    "T12 vertebra healthy",
    "T12 vertebra anomaly block vertebra",
    "T12 vertebra anomaly butterfly vertebra",
    "L1 vertebra healthy",
    "L1 vertebra anomaly block vertebra",
    "L1 vertebra anomaly butterfly vertebra",
    "L2 vertebra healthy",
    "L2 vertebra anomaly block vertebra",
    "L2 vertebra anomaly butterfly vertebra",
    "L3 vertebra healthy",
    "L3 vertebra anomaly block vertebra",
    "L3 vertebra anomaly butterfly vertebra",
    "L4 vertebra healthy",
    "L4 vertebra anomaly block vertebra",
    "L4 vertebra anomaly butterfly vertebra",
    "L5 vertebra healthy",
    "L5 vertebra anomaly block vertebra",
    "L5 vertebra anomaly butterfly vertebra"
]